import "pkg:/source/sl/ListMixin.bs"
import "pkg:/source/sl/RowItemScroller.bs"
import "pkg:/source/sl/RowItemViewManager.bs"
import "pkg:/source/sl/BaseRow.bs"

@node("DateHeaderRow", "sl_BaseRow")
class DateHeaderRow extends sl.BaseRow

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Public Fields
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  public focusedCellIndex = 0

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Views
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private menu

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Callbacks
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private function onMenuItemChange(index as integer)
    m.log.info("selected tab item", index)
    if index = 0
      m.sendRowData({ offset: -1 })
    else if index = 1
      m.sendRowData({ offset: 1 })
    end if
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Overridden Methods
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  protected override function createViews()
    bundle = m.global.styleManager@.loadBundle("pkg:/source/rows/DateHeaderRow.bundle")
    m.createViewsFromStyleJson(bundle.views)
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Row Delegate Methods
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private function onDidGainFocus(event as sl.ListEvent)
    ' ? "CR: onDidGainFocus " ; " " ; direction
    if m.owner.isFocused or m.owner.isChildFocused
      m.setFocus(m.menu)
    end if
  end function

end class
