import "pkg:/source/core/BaseClass.bs"
import "pkg:/source/sl/collectionView/BaseCollectionViewRow.bs"
import "pkg:/source/sl/collectionView/HorizontalRowLayout.bs"

namespace sl.collectionView
  class HorizontalRow extends sl.collectionView.BaseCollectionViewRow

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Initialize
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    function new(view as sl.collectionView.CollectionView, content as mc.types.node)
      super(view, content, "HorizontalRow")
      m.configure(content)
      m.layout = new sl.collectionView.HorizontalRowLayout(m)
    end function

  end class
end namespace
